[versions]
agp = "8.0.2"
kotlin = "1.9.23"
nexus-publish = "2.0.0-rc-1"
android-minSdk = "24"
android-compileSdk = "33"
# Kotlin(x)
coroutines = "1.8.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
ui-text-android = { group = "androidx.compose.ui", name = "ui-text-android", version = "1.6.7" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
